from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

d=Document(); s=d.sections[0]; s.page_width=Inches(8.5); s.page_height=Inches(11); s.top_margin=Inches(.7); s.bottom_margin=Inches(.65); s.left_margin=Inches(.8); s.right_margin=Inches(.8)
for n,sz,col in [('Title',28,'12295B'),('Heading 1',18,'12295B'),('Heading 2',13,'1D437F')]:
 st=d.styles[n]; st.font.name='Aptos Display'; st.font.size=Pt(sz); st.font.bold=True; st.font.color.rgb=RGBColor.from_string(col)
d.styles['Normal'].font.name='Aptos'; d.styles['Normal'].font.size=Pt(10.5); d.styles['Normal'].font.color.rgb=RGBColor.from_string('1A2233'); d.styles['Normal'].paragraph_format.space_after=Pt(6)
def p(x='',style=None): d.add_paragraph(x,style)
def bullets(xs):
 for x in xs: p(x,'List Bullet')
def tbl(rows):
 t=d.add_table(rows=1,cols=len(rows[0])); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.style='Table Grid'
 for i,x in enumerate(rows[0]):
  c=t.rows[0].cells[i]; c.text=x; sh=OxmlElement('w:shd'); sh.set(qn('w:fill'),'1D437F'); c._tc.get_or_add_tcPr().append(sh)
  for r in c.paragraphs[0].runs: r.font.bold=True; r.font.color.rgb=RGBColor(255,255,255); r.font.size=Pt(9)
 for ri,row in enumerate(rows[1:]):
  cs=t.add_row().cells
  for i,x in enumerate(row): cs[i].text=x; [setattr(r.font,'size',Pt(9)) for r in cs[i].paragraphs[0].runs]
 return t
d.add_paragraph('GST Portal Product Feature Guide','Title'); p('Product language for the redesigned GST filing, reconciliation, ledger and refund experience'); p('Version 1.0  |  September 2026  |  Prototype product documentation')
d.add_heading('Product overview',1); p('The redesigned GST Portal is a guided compliance workspace for e-invoice-enabled B2B taxpayers. It brings sales returns, purchase reconciliation, tax payment, ledgers and refund claims into one connected flow. The product promise is simple: every number has a source, every automated decision is explainable, and every consequential action is confirmed before it happens.'); p('This guide explains the product value, major features and end-to-end workflows. The current experience is a GST Portal redesign prototype with synthetic data and simulated filing outcomes; it is not the live government portal.')
d.add_heading('Who the product serves',1); tbl([['User need','Product response'],['Accountants using Excel, Tally or SAP','Familiar upload, validation and review workflows with downloadable templates.'],['Businesses filing monthly returns','A period workspace connecting GSTR-1, IMS, GSTR-3B and ledgers in sequence.'],['Teams managing refunds','A guided RFD-01 flow with eligibility, evidence, computation and tracking.'],['Reviewers who need confidence','Source labels, audit-friendly history, warnings and confirmations.']])
d.add_heading('End-to-end experience',1); p('A typical journey starts on Dashboard, moves to Returns for GSTR-1, continues to Purchases / IMS, then opens GSTR-3B after its prerequisites are complete. Filing GSTR-3B updates the ledgers and records payment activity. Users can then trace every movement from the Ledgers page.'); tbl([['Stage','Outcome'],['Dashboard','See due work, filed work, amounts and the next recommended action.'],['Returns','Select the financial period and open the required return.'],['GSTR-1','Upload, validate, categorise, reconcile and file outward supplies.'],['Purchases / IMS','Review inward invoices, decide exceptions and finalise GSTR-2B.'],['GSTR-3B','Review liability and ITC, offset tax, pay cash shortfall and file.'],['Ledgers','Trace credit, cash and liability balances to their sources.'],['Refunds','Prepare and track an Inverted Duty Structure claim when eligible.']])
d.add_heading('1 Secure entry and navigation',1); p('Users sign in with email and password or choose one of three demo profiles: a monthly filer, a refund claimant or a new account. The header keeps the company name and GSTIN visible. Navigation provides Dashboard, Returns, Purchases / IMS, Ledgers, Refunds and Annual Return. The IMS badge shows inward invoices needing attention. A consistent footer identifies the prototype and synthetic data.')
d.add_heading('2 Dashboard',1); p('The Dashboard is the operational starting point. It converts filing obligations into a current-period to-do list and keeps important money figures visible.'); bullets(['GSTR-1, IMS and GSTR-3B actions with status, due dates, days remaining and direct links.','Refund action and claimable amount only when the account is eligible.','Cash ledger balance, credit ledger balance, refund claimable amount or outstanding liability.','Coming-due table for return and refund deadlines.','Useful empty states for new accounts, with a clear first action.']); p('The Dashboard changes as work is completed. Filing GSTR-1, for example, changes its row to Filed and points the user to the next step.')
d.add_heading('3 Returns hub and period control',1); p('Returns is the period control centre. Users select financial year, quarter and period, then search to load the return context. Past filed periods remain available in a read-only state.'); bullets(['Period card with GSTR-1 and GSTR-3B status and due dates.','All outward-supply categories, plus automatically prepared Table 12 and Table 13.','Document count, taxable value, tax and Open action for each category.','Nil return filing only when no committed sales documents exist, with explicit confirmation.'])
d.add_heading('4 GSTR-1 preparation and filing',1); d.add_heading('Upload and validation',2); p('Users download an Excel template with a Read me sheet, examples and controlled dropdowns, then upload invoice lines. Sample data supports demos without a file picker. Validation reports state rows read, invoices found and the exact fixes required. Partially valid files continue to Review with errors visible.'); d.add_heading('Review and categorisation',2); p('Review is the trust step. Error rows appear first, followed by invoices grouped into suggested categories. Each suggestion includes a reason such as “GSTIN present → B2B”. Users can override eligible categories, and overrides are retained. Commit states exactly how many invoices and categories will be saved and stays blocked while errors remain.'); d.add_heading('Workspace and filing',2); p('The workspace expands category rows to show invoice detail. Table 12 is derived from invoice lines and is read-only. Table 13 detects document series and asks the user to confirm missing-number reasons. Filing is enabled only when errors are cleared and the series is confirmed; after filing the period becomes read-only and an ARN is shown.')
d.add_heading('5 E-invoice and ERP reconciliation',1); p('Data provenance stays visible when records come from the IRP or an ERP. Imported e-invoices carry an IRN badge and date, while ERP rows are identified separately. Imports are idempotent. Editing a signed e-invoice warns that the IRN provenance will be detached; optional UTP mode demonstrates recording a delta against the signed invoice.')
d.add_heading('6 Purchases and IMS',1); p('Purchases / IMS gives users a decision-oriented view of inward invoices before GSTR-3B. The preview explains what would happen if no action is taken: untouched eligible invoices become accepted by silence and flow into the ITC claim.'); bullets(['Review supplier, invoice, value, ITC and whether the invoice exists in purchase records.','Accept, reject or keep pending, individually or in bulk for matched invoices.','Warnings before rejecting a credit note and expiry dates for pending rows.','Finalise GSTR-2B into available, unavailable and rejected sections.','Lock all actions after GSTR-3B filing with a clear explanation.'])
d.add_heading('7 GSTR-3B and payment',1); p('GSTR-3B is sequenced after GSTR-1 and IMS. If either is incomplete, the product explains the prerequisite and links to it.'); bullets(['Pre-filled liability, nil/exempt supplies, reverse charge and ITC with source labels.','Suggested set-off by tax head and cash required, with editable payment inputs.','Prototype challan creation when cash is short.','Once-only offset action per period.','Filing records payment and ledger movements, then links to Ledgers.'])
d.add_heading('8 Ledgers',1); p('Ledgers turns filing activity into an understandable financial statement across Credit ledger, Cash ledger and Liability register. Balance cards show IGST, CGST, SGST and cess by head. Monthly statements show dates, descriptions, source links, debits, credits and running balances. Cash minor heads and liability discharge pairs are included, and visible rows can be downloaded as Excel.')
d.add_page_break(); d.add_heading('9 Refunds for Inverted Duty Structure',1); p('Refunds is the flagship experience for cases where purchase tax rates are higher than sales tax rates. The product exposes the legal and financial logic so users understand both eligibility and amount.'); tbl([['Step','Experience'],['R1 Home','Claimable amount, period, reason and claims history.'],['R2 Eligibility','Automated return checks and a two-year deadline countdown.'],['R3 Classify purchases','Confirm or override inputs, services and capital goods; surface blocked-credit suggestions.'],['R4 Inversion check','Review evidence by output HSN and confirm or exclude flagged patterns.'],['R5 Compute','See turnover, tax, net ITC, Rule 89(5) maximum and lowest-of-three result.'],['R6 Statements and file','Review generated Statement 1A and Annexure B, bank account and declarations.'],['R7 Tracker','Follow acknowledgement, provisional refund, sanction, payment and disbursement.']])
p('Before filing, the product explains the consequence: the claim amount leaves the credit ledger in the prototype and supporting purchase invoices are locked until a decision. Deficiency or rejection paths show re-credit and unlock effects. Officer controls are demonstration-only and labelled accordingly.')
d.add_heading('10 Annual Return',1); p('Annual Return provides a thin GSTR-9 experience. It summarises outward supplies, ITC and tax paid from filed returns, and auto-fills the annual HSN summary from Table 12. One editable tax-payable cell demonstrates persistent highlighting of differences.')
d.add_heading('11 Profile and payment history',1); p('The profile brings registration details, places of business, signatories, bank accounts, filing history, AATO and e-invoicing applicability together. Payment records created during GSTR-3B filing remain connected to the return and ledger history.')
d.add_heading('Product principles',1); bullets(['Explain before asking the user to decide.','Show the source of every important number.','Use explicit confirmations for filing, rejection, category changes and money movement.','Preserve read-only states after filing or refund locking.','Make empty, blocked and simulated states understandable in plain language.'])
d.add_heading('Prototype scope and limitations',1); p('This guide describes the current prototype. All data, amounts, dates, ARNs, filing outcomes and officer outcomes are synthetic or simulated. The experience demonstrates workflow and product behaviour; it does not submit information to the government portal. Advanced workflows such as GSTR-9C, notices, QRMP/IFF, interest and late-fee computation, and refund categories beyond Inverted Duty Structure are outside the current scope.')
d.add_heading('Recommended demo stories',1); p('Monthly filing: sign in as Aarohan Systems, upload sample invoices, fix the validation issue, commit and file GSTR-1, review IMS, finalise GSTR-2B, file GSTR-3B and open Ledgers. Refund: sign in as Meridian Packaging, follow the refund steps from Dashboard through the tracker and show the resulting ledger timeline.')
d.save('GST_Portal_Product_Feature_Guide.docx')
